[package]
name = "counter"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "counter"
path = "src/main.rs"

[dependencies]
app.workspace = true
window-manager.workspace = true
io-ring.workspace = true
wayland = { workspace = true, features = ["client"] }
ui = { path = "../ui" }
utils = { path = "../utils" }
widgets = { path = "../widgets" }
